# Generated by Django 4.1.4 on 2023-11-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('path', models.JSONField(blank=True, null=True)),
                ('heuristicCost', models.IntegerField()),
                ('travelTime', models.IntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('hour', models.IntegerField(blank=True, null=True)),
                ('minute', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
